from __future__ import annotations

# Curated, high-frequency robotics institutions used for paper-level matching.
# Keep entries canonical so they can double as aliases when expanded.
COMMON_ROBOTICS_INSTITUTIONS: list[str] = [
    "Carnegie Mellon University",
    "Massachusetts Institute of Technology",
    "Stanford University",
    "University of California, Berkeley",
    "University of California, San Diego",
    "University of Washington",
    "Georgia Institute of Technology",
    "University of Michigan",
    "University of Pennsylvania",
    "Columbia University",
    "Cornell University",
    "Princeton University",
    "Johns Hopkins University",
    "California Institute of Technology",
    "University of Southern California",
    "University of Texas at Austin",
    "University of Illinois Urbana-Champaign",
    "Northwestern University",
    "Brown University",
    "Yale University",
    "Harvard University",
    "University of Oxford",
    "University of Cambridge",
    "Imperial College London",
    "ETH Zurich",
    "EPFL",
    "Technical University of Munich",
    "University of Stuttgart",
    "RWTH Aachen University",
    "University of Freiburg",
    "University of Zurich",
    "Delft University of Technology",
    "KTH Royal Institute of Technology",
    "Aalto University",
    "University of Copenhagen",
    "Politecnico di Milano",
    "University of Bologna",
    "University of Tokyo",
    "University of Osaka",
    "Tohoku University",
    "Kyoto University",
    "Tokyo Institute of Technology",
    "University of Tsukuba",
    "Korea Advanced Institute of Science and Technology",
    "Seoul National University",
    "POSTECH",
    "Yonsei University",
    "Nanyang Technological University",
    "National University of Singapore",
    "Hong Kong University of Science and Technology",
    "The University of Hong Kong",
    "The Chinese University of Hong Kong",
    "Tsinghua University",
    "Peking University",
    "Shanghai Jiao Tong University",
    "Zhejiang University",
    "Xi'an Jiaotong University",
    "University of Science and Technology of China",
    "Harbin Institute of Technology",
    "Chinese Academy of Sciences",
    "University of Chinese Academy of Sciences",
    "Mohamed bin Zayed University of Artificial Intelligence",
    "Idiap Research Institute",
    "Toyota Research Institute",
    "NVIDIA",
    "Google DeepMind",
    "Google Research",
    "Microsoft Research",
    "Meta AI",
    "OpenAI",
    "Boston Dynamics",
    "Allen Institute for AI",
]

