from __future__ import annotations

# Curated, high-frequency robotics institutions used for paper-level matching.
# Entries can be plain canonical strings or dictionaries with explicit aliases.
COMMON_ROBOTICS_INSTITUTIONS: list[object] = [
    {"canonical": "Carnegie Mellon University", "aliases": ["CMU", "Carnegie Mellon", "RI at CMU"]},
    {"canonical": "Massachusetts Institute of Technology", "aliases": ["MIT", "M.I.T."]},
    {"canonical": "Stanford University", "aliases": ["Stanford", "SAIL"]},
    {"canonical": "University of California, Berkeley", "aliases": ["UC Berkeley", "UCB", "Berkeley"]},
    {"canonical": "University of California, San Diego", "aliases": ["UC San Diego", "UCSD"]},
    {"canonical": "University of California, Los Angeles", "aliases": ["UCLA", "UC Los Angeles"]},
    {"canonical": "University of Washington", "aliases": ["UW", "UDub"]},
    {"canonical": "Georgia Institute of Technology", "aliases": ["Georgia Tech", "Gatech"]},
    {"canonical": "University of Michigan", "aliases": ["U-M", "UMich", "University of Michigan, Ann Arbor"]},
    {"canonical": "University of Pennsylvania", "aliases": ["UPenn", "Penn", "U Penn"]},
    "Columbia University",
    "Cornell University",
    "Princeton University",
    "Johns Hopkins University",
    {"canonical": "California Institute of Technology", "aliases": ["Caltech"]},
    {"canonical": "University of Southern California", "aliases": ["USC"]},
    {"canonical": "University of Texas at Austin", "aliases": ["UT Austin"]},
    {"canonical": "University of Illinois Urbana-Champaign", "aliases": ["UIUC", "Illinois Urbana-Champaign", "U of I Urbana-Champaign", "University of Illinois at Urbana-Champaign"]},
    "Northwestern University",
    "Brown University",
    "Yale University",
    "Harvard University",
    {"canonical": "University of Maryland, College Park", "aliases": ["UMD", "University of Maryland"]},
    {"canonical": "The Ohio State University", "aliases": ["Ohio State University", "OSU"]},
    "Virginia Tech",
    {"canonical": "University of Minnesota, Twin Cities", "aliases": ["University of Minnesota"]},
    {"canonical": "University of Toronto", "aliases": ["U of T", "UofT"]},
    {"canonical": "University of Waterloo", "aliases": ["UWaterloo"]},
    "McGill University",
    {"canonical": "University of Alberta", "aliases": ["UAlberta"]},
    {"canonical": "University of Oxford", "aliases": ["Oxford"]},
    {"canonical": "University of Cambridge", "aliases": ["Cambridge"]},
    {"canonical": "Imperial College London", "aliases": ["Imperial", "Imperial College"]},
    {"canonical": "University of Edinburgh", "aliases": ["Edinburgh Centre for Robotics"]},
    "University of Bristol",
    {"canonical": "ETH Zurich", "aliases": ["ETH Zürich", "ETHZ", "ETH"]},
    "EPFL",
    {"canonical": "Technical University of Munich", "aliases": ["TUM", "TU Munich", "Technische Universitat Munchen", "Technische Universitaet Muenchen", "TUM Munich"]},
    {"canonical": "University of Stuttgart", "aliases": ["Uni Stuttgart"]},
    {"canonical": "RWTH Aachen University", "aliases": ["RWTH Aachen", "RWTH"]},
    "University of Freiburg",
    "University of Zurich",
    {"canonical": "Delft University of Technology", "aliases": ["TU Delft", "Delft Tech"]},
    "KTH Royal Institute of Technology",
    "Aalto University",
    "University of Copenhagen",
    "Politecnico di Milano",
    "University of Bologna",
    {"canonical": "Max Planck Institute for Intelligent Systems", "aliases": ["MPI-IS", "MPI IS", "Max Planck Institute"]},
    {"canonical": "German Research Center for Artificial Intelligence", "aliases": ["DFKI"]},
    {"canonical": "INRIA", "aliases": ["Inria", "French Institute for Research in Computer Science and Automation"]},
    {"canonical": "LAAS-CNRS", "aliases": ["LAAS", "Laboratoire d'Analyse et d'Architecture des Systèmes"]},
    {"canonical": "University of Tokyo", "aliases": ["The University of Tokyo", "UTokyo"]},
    "University of Osaka",
    "Tohoku University",
    "Kyoto University",
    {"canonical": "Tokyo Institute of Technology", "aliases": ["Tokyo Tech", "Institute of Science Tokyo", "Science Tokyo"]},
    "University of Tsukuba",
    {"canonical": "Korea Advanced Institute of Science and Technology", "aliases": ["KAIST"]},
    "Seoul National University",
    {"canonical": "POSTECH", "aliases": ["Pohang University of Science and Technology"]},
    {"canonical": "Yonsei University", "aliases": ["Yonsei"]},
    {"canonical": "Nanyang Technological University", "aliases": ["NTU"]},
    {"canonical": "National University of Singapore", "aliases": ["NUS"]},
    {"canonical": "Hong Kong University of Science and Technology", "aliases": ["HKUST", "HKUST Guangzhou", "HKUST(GZ)"]},
    {"canonical": "The University of Hong Kong", "aliases": ["HKU"]},
    {"canonical": "The Chinese University of Hong Kong", "aliases": ["CUHK"]},
    {"canonical": "Tsinghua University", "aliases": ["THU"]},
    {"canonical": "Peking University", "aliases": ["PKU"]},
    {"canonical": "Shanghai Jiao Tong University", "aliases": ["SJTU"]},
    {"canonical": "Zhejiang University", "aliases": ["ZJU"]},
    {"canonical": "Xi'an Jiaotong University", "aliases": ["XJTU"]},
    {"canonical": "University of Science and Technology of China", "aliases": ["USTC"]},
    {"canonical": "Harbin Institute of Technology", "aliases": ["HIT"]},
    {"canonical": "Beihang University", "aliases": ["Beijing University of Aeronautics and Astronautics", "BUAA"]},
    {"canonical": "Chinese Academy of Sciences", "aliases": ["CAS"]},
    {"canonical": "University of Chinese Academy of Sciences", "aliases": ["UCAS"]},
    "Mohamed bin Zayed University of Artificial Intelligence",
    "Idiap Research Institute",
    "Toyota Research Institute",
    {"canonical": "NVIDIA", "aliases": ["NVIDIA Research", "NVIDIA Corporation"]},
    {"canonical": "Google DeepMind", "aliases": ["DeepMind", "Google Deepmind"]},
    "Google Research",
    {"canonical": "Microsoft Research", "aliases": ["MSR"]},
    {"canonical": "Meta AI", "aliases": ["FAIR", "Facebook AI Research"]},
    {"canonical": "OpenAI", "aliases": ["OpenAI Research"]},
    {"canonical": "Boston Dynamics", "aliases": ["Boston Dynamics AI Institute"]},
    "Allen Institute for AI",
    {"canonical": "Amazon Robotics", "aliases": ["Amazon Alexa AI", "Amazon Lab126"]},
    "Intrinsic",
    "Agility Robotics",
    "Figure AI",
    "1X Technologies",
    "University of Hyogo",
    "Pennsylvania State University",
    "University of Klagenfurt",
    "Chalmers University of Technology",
    {"canonical": "University of Gothenburg", "aliases": ["Gothenburg University"]},
    {"canonical": "University of Electronic Science and Technology of China", "aliases": ["UESTC"]},
    "Sichuan University",
    "Chuo University",
    "Takenaka Corporation",
    "Dexmal Inc.",
    "General Bionix, Inc.",

    {"canonical": "University of California, Davis", "aliases": ["UC Davis", "UCD"]},
    {"canonical": "University of California, Santa Barbara", "aliases": ["UC Santa Barbara", "UCSB"]},
    {"canonical": "University of California, Irvine", "aliases": ["UC Irvine", "UCI"]},
    {"canonical": "University of California, Santa Cruz", "aliases": ["UC Santa Cruz", "UCSC"]},
    {"canonical": "University of California, Riverside", "aliases": ["UC Riverside", "UCR"]},
    {"canonical": "University of Colorado Boulder", "aliases": ["CU Boulder"]},
    {"canonical": "University of Colorado Denver", "aliases": ["CU Denver"]},
    {"canonical": "Colorado School of Mines", "aliases": ["Mines"]},
    {"canonical": "University of Arizona", "aliases": ["UArizona"]},
    {"canonical": "Arizona State University", "aliases": ["ASU"]},
    {"canonical": "University of New Mexico", "aliases": ["UNM"]},
    {"canonical": "University of Nevada, Reno", "aliases": ["UNR"]},
    {"canonical": "University of Utah", "aliases": ["U of U"]},
    {"canonical": "Brigham Young University", "aliases": ["BYU"]},
    {"canonical": "University of Kansas", "aliases": ["KU"]},
    {"canonical": "Iowa State University", "aliases": ["ISU"]},
    {"canonical": "University of Iowa", "aliases": ["UIowa"]},
    {"canonical": "University of Nebraska-Lincoln", "aliases": ["UNL"]},
    {"canonical": "University of Missouri", "aliases": ["Mizzou"]},
    {"canonical": "University of Wisconsin-Madison", "aliases": ["UW Madison"]},
    {"canonical": "University of Wisconsin-Milwaukee", "aliases": ["UWM"]},
    {"canonical": "Michigan State University", "aliases": ["MSU"]},
    {"canonical": "Purdue University", "aliases": ["Purdue"]},
    {"canonical": "Indiana University Bloomington", "aliases": ["IU Bloomington"]},
    {"canonical": "University of Notre Dame", "aliases": ["Notre Dame"]},
    {"canonical": "University of Kentucky", "aliases": ["UKY"]},
    {"canonical": "University of Louisville", "aliases": ["UofL"]},
    {"canonical": "University of Tennessee, Knoxville", "aliases": ["UTK"]},
    {"canonical": "Vanderbilt University", "aliases": ["Vanderbilt"]},
    {"canonical": "Duke University", "aliases": ["Duke"]},
    {"canonical": "University of North Carolina at Chapel Hill", "aliases": ["UNC Chapel Hill", "UNC"]},
    {"canonical": "North Carolina State University", "aliases": ["NC State", "NCSU"]},
    {"canonical": "University of South Carolina", "aliases": ["UofSC"]},
    {"canonical": "Clemson University", "aliases": ["Clemson"]},
    {"canonical": "University of Florida", "aliases": ["UF"]},
    {"canonical": "University of Central Florida", "aliases": ["UCF"]},
    {"canonical": "Florida State University", "aliases": ["FSU"]},
    {"canonical": "University of South Florida", "aliases": ["USF"]},
    {"canonical": "University of Miami", "aliases": ["Miami University", "UMiami"]},
    {"canonical": "Rice University", "aliases": ["Rice"]},
    {"canonical": "Texas A&M University", "aliases": ["TAMU"]},
    {"canonical": "University of Houston", "aliases": ["UH"]},
    {"canonical": "University of Texas at Dallas", "aliases": ["UT Dallas", "UTD"]},
    {"canonical": "University of Texas at Arlington", "aliases": ["UTA"]},
    {"canonical": "University of Texas at San Antonio", "aliases": ["UTSA"]},
    {"canonical": "Baylor University", "aliases": ["Baylor"]},
    {"canonical": "Tufts University", "aliases": ["Tufts", "Tufts ME"]},
    {"canonical": "Northeastern University", "aliases": ["Northeastern"]},
    {"canonical": "Boston University", "aliases": ["BU"]},
    {"canonical": "Worcester Polytechnic Institute", "aliases": ["WPI"]},
    {"canonical": "Rensselaer Polytechnic Institute", "aliases": ["RPI"]},
    {"canonical": "Rochester Institute of Technology", "aliases": ["RIT"]},
    {"canonical": "University at Buffalo", "aliases": ["SUNY Buffalo", "UB"]},
    {"canonical": "Stony Brook University", "aliases": ["SUNY Stony Brook"]},
    {"canonical": "University of Rochester", "aliases": ["URochester"]},
    {"canonical": "Syracuse University", "aliases": ["Syracuse"]},
    {"canonical": "Stevens Institute of Technology", "aliases": ["Stevens"]},
    {"canonical": "Lehigh University", "aliases": ["Lehigh"]},
    {"canonical": "Temple University", "aliases": ["Temple"]},
    {"canonical": "Rutgers University", "aliases": ["Rutgers"]},
    {"canonical": "New Jersey Institute of Technology", "aliases": ["NJIT"]},
    {"canonical": "Drexel University", "aliases": ["Drexel"]},
    {"canonical": "George Washington University", "aliases": ["GWU"]},
    {"canonical": "George Mason University", "aliases": ["GMU"]},
    {"canonical": "University of Virginia", "aliases": ["UVA"]},
    {"canonical": "Old Dominion University", "aliases": ["ODU"]},
    {"canonical": "University of Delaware", "aliases": ["UDel"]},
    {"canonical": "University of Massachusetts Amherst", "aliases": ["UMass Amherst"]},
    {"canonical": "University of Connecticut", "aliases": ["UConn"]},
    {"canonical": "Queen's University", "aliases": ["Queens University"]},
    {"canonical": "Université de Montréal", "aliases": ["University of Montreal", "UdeM"]},
    {"canonical": "Polytechnique Montréal", "aliases": ["Polytechnique Montreal"]},
    {"canonical": "Laval University", "aliases": ["Université Laval", "ULaval"]},
    {"canonical": "University of British Columbia", "aliases": ["UBC"]},
    {"canonical": "Simon Fraser University", "aliases": ["SFU"]},
    {"canonical": "University of Victoria", "aliases": ["UVic"]},
    {"canonical": "Concordia University", "aliases": ["Concordia"]},
    {"canonical": "University of Calgary", "aliases": ["UCalgary"]},
    {"canonical": "University of Ottawa", "aliases": ["uOttawa"]},
    {"canonical": "Carleton University", "aliases": ["Carleton"]},
    {"canonical": "University of Manitoba", "aliases": ["UManitoba"]},
    {"canonical": "Université de Sherbrooke", "aliases": ["University of Sherbrooke"]},
    {"canonical": "University College London", "aliases": ["UCL"]},
    {"canonical": "King's College London", "aliases": ["KCL"]},
    {"canonical": "University of Southampton", "aliases": ["Southampton"]},
    {"canonical": "University of Birmingham", "aliases": ["Birmingham"]},
    {"canonical": "University of Manchester", "aliases": ["Manchester"]},
    {"canonical": "University of Leeds", "aliases": ["Leeds"]},
    {"canonical": "University of Sheffield", "aliases": ["Sheffield"]},
    {"canonical": "University of Glasgow", "aliases": ["Glasgow"]},
    {"canonical": "Heriot-Watt University", "aliases": ["Heriot Watt"]},
    {"canonical": "King Abdullah University of Science and Technology", "aliases": ["KAUST"]},
    {"canonical": "Australian National University", "aliases": ["ANU"]},
    {"canonical": "University of Sydney", "aliases": ["USYD"]},
    {"canonical": "University of New South Wales", "aliases": ["UNSW"]},
    {"canonical": "Monash University", "aliases": ["Monash"]},
    {"canonical": "University of Melbourne", "aliases": ["UniMelb"]},
    {"canonical": "University of Queensland", "aliases": ["UQ"]},
    {"canonical": "Queensland University of Technology", "aliases": ["QUT"]},
    {"canonical": "University of Adelaide", "aliases": ["Adelaide"]},
    {"canonical": "University of Auckland", "aliases": ["UoA"]},
    {"canonical": "Auckland University of Technology", "aliases": ["AUT"]},
    {"canonical": "Indian Institute of Science", "aliases": ["IISc"]},
    {"canonical": "Indian Institute of Technology Bombay", "aliases": ["IIT Bombay", "IITB"]},
    {"canonical": "Indian Institute of Technology Delhi", "aliases": ["IIT Delhi", "IITD"]},
    {"canonical": "Indian Institute of Technology Madras", "aliases": ["IIT Madras", "IITM"]},
    {"canonical": "Indian Institute of Technology Kanpur", "aliases": ["IIT Kanpur", "IITK"]},
    {"canonical": "Indian Institute of Technology Kharagpur", "aliases": ["IIT Kharagpur", "IITKGP"]},
    {"canonical": "Indian Institute of Technology Hyderabad", "aliases": ["IIT Hyderabad", "IITH"]},
    {"canonical": "Technion – Israel Institute of Technology", "aliases": ["Technion"]},
    {"canonical": "Tel Aviv University", "aliases": ["TAU"]},
    {"canonical": "Hebrew University of Jerusalem", "aliases": ["HUJI"]},
    {"canonical": "Ben-Gurion University of the Negev", "aliases": ["BGU"]},
    {"canonical": "Sapienza University of Rome", "aliases": ["Sapienza"]},
    {"canonical": "University of Naples Federico II", "aliases": ["Federico II"]},
    {"canonical": "University of Genoa", "aliases": ["UNIGE"]},
    {"canonical": "University of Padua", "aliases": ["UniPD"]},
    {"canonical": "Scuola Superiore Sant'Anna", "aliases": ["Sant'Anna School"]},
    {"canonical": "KU Leuven", "aliases": ["Katholieke Universiteit Leuven"]},
    {"canonical": "Eindhoven University of Technology", "aliases": ["TU Eindhoven", "TU/e"]},
    {"canonical": "Uppsala University", "aliases": ["Uppsala"]},
    {"canonical": "Lund University", "aliases": ["Lund"]},
    {"canonical": "Norwegian University of Science and Technology", "aliases": ["NTNU"]},
    {"canonical": "University of Oslo", "aliases": ["UiO"]},
    {"canonical": "Technical University of Denmark", "aliases": ["DTU"]},
    {"canonical": "Czech Technical University in Prague", "aliases": ["CTU Prague"]},
    {"canonical": "Warsaw University of Technology", "aliases": ["WUT"]},
    {"canonical": "National Taiwan University", "aliases": ["NTU Taiwan"]},
    {"canonical": "National Tsing Hua University", "aliases": ["NTHU"]},
    {"canonical": "National Yang Ming Chiao Tung University", "aliases": ["NYCU"]},
    {"canonical": "Academia Sinica", "aliases": ["AS"]},
    "Honda Research Institute",
    "Sony AI",
    "ByteDance Research",
    "Huawei Noah's Ark Lab",
    "Tencent Robotics X",
    "Samsung Research",
    "Bosch Research",
    "ABB Robotics",
    "Siemens",
    "Mitsubishi Electric Research Laboratories",
    "NAVER LABS",
    "Autonomous University of Barcelona",
    "University of Twente",
    "Vrije Universiteit Amsterdam",
    "Heidelberg University",
    "Karlsruhe Institute of Technology",
    "University of Trento",
    "Istituto Italiano di Tecnologia",
    "University of Pisa",
    "National University of Defense Technology",

    "Brigham Young University",
    "Purdue University",
    {"canonical": "Rice University", "aliases": ["Rice"]},
    "Middle East Technical University",
    "Nara Institute of Science and Technology",
    "Paderborn University",
    {"canonical": "Northeastern University", "aliases": ["Northeastern"]},
    "Technology Innovation Institute",
    {"canonical": "Microsoft Spatial AI Lab", "aliases": ["MSAI Lab"]},
    "Lamarr Institute",
    "Zhongguancun Laboratory",

]
